# Generated by Django 4.1 on 2025-02-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
